### ISSUE TITLE
Trouble getting it working on Windows

### ISSUE THREAD

**Issue by olie304** [ucnv/pnglitch#6]
Currently testing the example scripts to see if I can get those to work first. New to Ruby and I don't really understand what is going on but the images come out completely broken every time. I get no errors.

This is the script I am testing with: https://pastebin.com/ZAzhtS8b

Edit: Looks like it just deletes everything but the header and saves it.
Edit2:  Using some of the example scripts like sub and up lead to this: https://pastebin.com/pB3MxCp7

**Comment by girardof** [comment]
The issue was fixed by https://github.com/ucnv/pnglitch/commit/6730e650b62cecd20fd60dc93edbcd914e688fd9 but the gem is not updated.

**Comment by ucnv** [comment]
Released finally. Thank you.

**Comment by olie304** [comment]
Nice
